#! /bin/bash
# Script that creates Java classpath before starting vi

# Make list of jars that are needed for compiling and running tests
JUNIT_JARS=./libs/junit-4.12.jar:./libs/hamcrest-core-1.3.jar
SOOT_JARS=`ls -d -1 ./libs/*.jar | tr '\n' ':'`
JAVA_HOME_JARS=`ls -d -1 $JAVA_HOME/jre/lib/*.jar | tr '\n' ':'`
JDI_JARS=$JAVA_HOME/lib/tools.jar

CLASSPATH=$JUNIT_JARS:$SOOT_JARS:$JAVA_HOME_JARS:$JDI_JARS:. vi $@
